g_cancer<- read.graph("~/Project_Data_Files/Bone_Cell/Cancer/Igraph_Cancer_Edges.txt",directed=F)
#fgcC<- fastgreedy.community(g_cancer)
fgcC<- multilevel.community(g_cancer)
df<- as.data.frame(0:350)
source('~/Project_Data_Files/iterative_clustering.R')
unlink("~/Project_Data_Files/vertexCount.txt")
iterative.clustering(fgcC,g_cancer,df,1)
graph.setup()
a<-getwd()
setwd("~/Project_Data_Files")
file.rename("final.csv","final_Cancer.csv")
setwd(a)