library(igraph)
g_normal<- read.graph("~/Project_Data_Files/Bone_Cell/Normal/Igraph_Normal_Edges.txt",directed=F)
#fgcN<- multilevel.community(g_normal)
fgcN<- fastgreedy.community(g_normal)
df<- as.data.frame(0:191)
source('~/Project_Data_Files/iterative_clustering.R')
unlink("vertexCount.txt")
iterative.clustering(fgcN,g_normal,df,1)
graph.setup()
a<-getwd()
setwd("~/Project_Data_Files")
file.rename("final.csv","final_Normal.csv")
setwd(a)